CREATE TABLE TARGET_HOSTS (
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(60) NOT NULL, 
  ADDRESS VARCHAR(40) NOT NULL,
  REGISTERED DATE,
  UNIQUE UQ_TARGET_HOSTS_1 (ID), 
  UNIQUE UQ_TARGET_HOSTS_2 (NAME), 
  PRIMARY KEY (ID) 
); 

CREATE TABLE TARGET_GROUPS (
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(60) NOT NULL, 
  UNIQUE UQ_TARGET_GROUPS_1 (ID), 
  UNIQUE UQ_TARGET_GROUPS_2 (NAME), 
  PRIMARY KEY (ID) 
); 

CREATE TABLE TASKS (
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(60) NOT NULL, 
  SCRIPT_NAME VARCHAR(60), 
  UNIQUE UQ_TASKS_1 (ID), 
  UNIQUE UQ_TASKS_2 (NAME), 
  PRIMARY KEY (ID) 
);

CREATE TABLE TASK_EXECUTIONS (
  ID VARCHAR(36) NOT NULL,
  TASK_ID VARCHAR(36) NOT NULL,
  SCHEDULED_START_TIME DATE,
  ACTUAL_START_TIME DATE,
  END_TIME DATE,
  UNIQUE UQ_TASK_EXECUTIONS_1 (ID), 
  CONSTRAINT FK_TASK_EXECUTIONS_1 FOREIGN KEY (TASK_ID)
    REFERENCES TASKS (ID) ON DELETE CASCADE,
  PRIMARY KEY (ID) 
);

