CREATE TABLE TARGET_HOSTS (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(60) NOT NULL, 
  ADDRESS VARCHAR(40) NOT NULL,
  REGISTERED DATE,
  UNIQUE UQ_TARGET_HOSTS_1 (NAME), 
  PRIMARY KEY (ID) 
); 
