CREATE TABLE TARGET_HOSTS (
  ID VARCHAR(36) NOT NULL,
  NAME VARCHAR(60) NOT NULL, 
  ADDRESS VARCHAR(40) NOT NULL,
  REGISTERED DATE,
  UNIQUE UQ_TARGET_HOSTS_1 (ID), 
  UNIQUE UQ_TARGET_HOSTS_2 (NAME), 
  PRIMARY KEY (ID) 
); 
